### ISSUE TITLE
Feature request: Allow configurable environment variables

### ISSUE THREAD

**Issue by madalinignisca** [opendevshop/devshop#128]
I think that it would be great to be able to setup server config variables per each "environment".

An example would be for using setting in **sites/all/settings.devshop.php** to use **getenv()** for getting credentials for S3 and other resources that I might want to automate the process for.

Something similar to what Heroku and others are offering:

![screen shot 2016-06-07 at 13 00 39](https://cloud.githubusercontent.com/assets/619561/15856801/e0a96826-2caf-11e6-9ad5-5449cf502b07.png)

**Comment by jonpugh** [comment]
That's a great idea.

There's already something similar for Aegir but it only sets Drupal variables, not environment variables.

https://www.drupal.org/project/hosting_variables

Perhaps we submit patches to that module to provide "environment variables" as well as drupal config? 

I'm sure including this module in devshop is a good idea, especially if it ends up having environment variables set as well.

**Comment by jonpugh** [comment]
This would make a great hook in Aegir provision itself 

We already have hooks to alter Apache vhost config and nginx, but having a simple hook to return environment variable for either would be awesome.

Let's patch Aegir itself to provide the hook, then we can add a module to hosting task extras.

I love the idea but I can't prioritize it for 1.0.0, but after that, let's do it.

**Comment by jonpugh** [comment]
:point_down:

**Comment by jonpugh** [comment]
This is possible to do with `.env` file now thanks to The issue here: https://www.drupal.org/project/provision/issues/3073299

We don't yet have this done in an automated way: Only the API docs example actually does anything. 

I would like to start standardizing on this: Using sites/X.com/drushrc.php for setting $_SERVER['db_name'] is not ideal. 

.env files have become pretty common practice.
