### ISSUE TITLE
How can i set to skip "Step 3: environments"?

### ISSUE THREAD

**Issue by LiangJ** [opendevshop/devshop#250]
How can i set to skip "Step 3: environments" when add project ?

Thanks

**Comment by jonpugh** [comment]
Hi @LiangJ 
I hadn't thought about this but I suppose it should be made possible.

Right now it's set as required because we try to verify the platforms before step 4. In step 4, we use the platform data to lookup available install profiles so users can be shown that profile in the "default install profile" field.

It would be possible but it would require some code changes to devmaster create wizard code. We would have to skip the field for default install profile, which I guess is fine. You can now change the default install profile later on in the project settings.

**Comment by LiangJ** [comment]
Thanks

**Comment by jonpugh** [comment]
Really, all we would have to do I think is:

- Remove check for "no environments" in step3.inc.
- Add a button to step 3 for "Skip: Add environments later".,
- Add a better display for a project that has no environments.

**Comment by jonpugh** [comment]
This will be resolved by removing the "install profile" field on the wizard, which can happen when we add "install_command"
