### ISSUE TITLE
"Error: cannot load node id 0 to find its context" when verifying platform

### ISSUE THREAD

**Issue by radimklaska** [opendevshop/devshop#26]
Steps to reproduce:
* install 0.5.2 or 0.x
* add new project
* when environments are verified, all verify tasks fail with "Error: cannot load node id 0 to find its context"

Probably related:
* https://github.com/opendevshop/devmaster/commit/8704c9ca9fd76f7f3800e366658d348497b36e03
* https://github.com/opendevshop/devmaster/commit/7aed1350b6dd505adeb9a9762e8081a876452a27
* https://www.drupal.org/node/1896184

**Comment by jonpugh** [comment]
Don't want to close until we can confirm it's fixed.

@radimklaska Can you try a fresh 0.x install and let me know that it works by closing this issue?  

Once someone confirms this fixes it I will push out a new release.

Thanks!

**Comment by radimklaska** [comment]
Sorry, still getting the same error. :(

**Comment by radimklaska** [comment]
Progress! When creating new project, on the first step, try some variations of "Project Code Name" like different lengths and/or strings containing a number.

Examples:
* qqq - works
* playground - fails (might be because of my previous tests)
* playground7 - fails

**Comment by jonpugh** [comment]
I've tested creating projects with both of those names and I didn't have any problems.

I am not sure what's wrong with your install.  This shouldn't have problems because of previous projects...

Each project, server, platform, and site node should have a row in the {hosting_context} table. It only does the saving to the table in hook_insert.

**Comment by radimklaska** [comment]
hosting_context looks normal... 
```
mysql> select * from hosting_context;
+-----+------------------------------+
| nid | name                         |
+-----+------------------------------+
| 184 | dev.qqq.mydevshop.tld        |
|  10 | hostmaster                   |
| 186 | live.qqq.mydevshop.tld       |
| 190 | platform_devmaster0x20151026 |
| 125 | platform_playground7_dev     |
| 127 | platform_playground7_live    |
| 129 | platform_playground7_stage   |
| 169 | platform_playground_dev      |
| 171 | platform_playground_live     |
| 173 | platform_playground_stage    |
| 178 | platform_qqq_dev             |
| 180 | platform_qqq_live            |
| 182 | platform_qqq_stage           |
| 176 | qqq                          |
|   4 | server_localhost             |
|   2 | server_master                |
| 188 | stage.qqq.mydevshop.tld      |
+-----+------------------------------+
```

I will try to do more debugging... @jlmeredith How is your test going?

**Comment by jlmeredith** [comment]
I attempted to run the 0.5.2 installer found here - https://raw.githubusercontent.com/opendevshop/devshop/0.5.2/install.sh - but the install failed.  

Here is the install output - http://pastebin.com/UMQZ3F5X

**Comment by radimklaska** [comment]
That looks like connections issues or Drupal.org downtime. I would just try it again.

**Comment by laroucheyouth** [comment]
Hi guys, just ran into this exact error when trying to setup my devshop server.

**Comment by jonpugh** [comment]
I think this should finally be squashed in 0.5.4, released today.

Give it a try?

This was a string of problems: The "Node 0" is the web_server. If you inspect your platform node, you'll see that it was missing it's web_server.

Once in a while, the form submission from Step 2: Settings was losing the data it submitted, which included "default environment servers". I still don't know exactly when this is happening, but I've got a rough Behat test to check for it.

Then, on Step 3: Environments, each environment gets a form element for it's "web_server". The code I wrote, if there was only one web_server, was to change the element to #type => value, but I set the value to the $project object's settings, which was (sometimes) missing from Step 2.  

So that is fixed. Single server devshops will always get their web_server set from now on, even if the settings form fails.  

I've also added a "Project info" block to the create wizard so you can see information about the project you are creating.

**Comment by laroucheyouth** [comment]
Wiped my install, re-installed a fresh 0.5.4 install. This time it worked! I was able to add my project properly.

**Comment by radimklaska** [comment]
Great, fresh 0.5.4 worked for me too. Thanks!

**Comment by jonpugh** [comment]
Great, closing.
