### ISSUE TITLE
Default PHP 7.1 or 7.2 out of box

### ISSUE THREAD

**Issue by philoSurfer** [opendevshop/devshop#301]
Given that all D8 composer builds are requiring a minimum of php 7.1, I think this should be in the default playbook.

**Comment by jonpugh** [comment]
> Given that all D8 composer builds are requiring a minimum of php 7.1, 
Not quite... PHP 5 is still technically "supported": https://www.drupal.org/docs/8/system-requirements/php-requirement.

> Realizing this is dependent on Aegir hostmaster. 
It's not actually dependant on "hostmaster", "hostmaster" is just Aegir's drupal distribution name.

We should make this part more clear, and add it to the docs.

### Support for various PHP Versions

As maintainers of DevShop, it is near impossible for us to support all PHP versions on all operating systems. DevShop is Drupal, so it will run anywhere Drupal can run.

Therefore, we don't (yet) force any changes to the PHP version, and always defer to the Operating Systems choice. 

If you are comfortable altering the OS packaging repos to change the PHP version of your server, feel free to do so.

Otherwise, please choose your OS based on your desired PHP version to ensure your host will always have the OS-supported version of PHP:

- PHP 5: Ubuntu 14
- PHP 7.0: Ubuntu 16.04
- PHP 7.1: Ubuntu 17.10
- PHP 7.2: Ubuntu 18.04

Once DevShop fully supports Docker natively (it's pretty close now: Please test https://www.drupal.org/project/hosting_docker)

I'm going to change this issue to be about documenting this problem.

**Comment by philoSurfer** [comment]
Ran into an issue with Ubuntu 18.0.4 
https://github.com/opendevshop/ansible-role-aegir-apache/pull/3 to try and fix

**Comment by jonpugh** [comment]
@philoSurfer This PR will make this much simpler and configurable on the fly: https://github.com/opendevshop/devmaster/pull/89

**Comment by jonpugh** [comment]
And I am attempting to fix all of the ansible issues and get 18.04 tests passing here: https://github.com/opendevshop/devshop/pull/315

**Comment by jonpugh** [comment]
@philoSurfer I am changing the plan, we can support multple PHP per server easily with PHP FPM.

I am working on a branch of provision that will allow easy selecting of php version but for now you can customize your system to do the following:

1. Install the version of PHP you want: https://www.linuxbabe.com/ubuntu/php-multiple-versions-ubuntu-16-04-17-10
2. Drop a file into /var/aegir/.drush/setphpfpm.drush.inc, and create a hook for `drush_hook_provision_apache_vhost_config` to print the needed Apache VHOST config from the blog post.

**Comment by jonpugh** [comment]
Actually you might be able to do this globally for apache, I don't have time to test. Give it a shot!

**Comment by cmcintosh** [comment]
Running into the following issue with 7.2:
Uncaught Error: Call to undefined function cache_get() in /var/aegir/devmaster-1.4.0/includes/module.inc:754

This is coming from just running drush @hostmaster status, but is the same everywhere. Any Ideas / thoughts?

**Comment by cmcintosh** [comment]
Some more testing, seems like downgrading the system to 7.1 allows drush to execute tasks for Hostmaster, however all site installs for Drupal 8 are failing.  guess best option is to upgrade those to 7.2 via multi php version method.  

Is there any estimate or plan for getting aegir/drush/opendevshop up to 7.2 as earlier versions are now getting deprecated?

**Comment by caldenjacobs** [comment]
@cmcintosh have you tried 
`drush @hm provision-verify
sudo service hosting-queued restart`
per https://www.drupal.org/project/hostmaster/issues/2945366?

Assuming that doesn't fix the problem, what is you might want to try adding the following to your Drupal 8 repository's composer.json: 
`"config": { "sort-packages": true, "platform": { "php": "7.2" } },`

I'm around and having a lazy Saturday morning if you want to do a quick Hangouts call to try to collaboratively troubleshoot :)

**Comment by jonpugh** [comment]
See #188. We will solve this.
