### ISSUE TITLE
New project creation is broken after update to Devshop 1.4.0

### ISSUE THREAD

**Issue by caldenjacobs** [opendevshop/devshop#311]
Verify Project task fails with:

`WD php: Error: Call to undefined function provision_process() in getBranchesAndTags() (line 92 of /var/aegir/devmaster-1.4.0/profiles/devmaster/modules/devshop/devshop_projects/drush/contexts.inc). `

`Drush command terminated abnormally due to an unrecoverable error.`

**Comment by hubdrop-user** [comment]
The latest provision must not be installed. Try `drush dl provision`.

I will work on this tonight and release 1.4.1.



On Oct 1, 2018 3:12 PM, "Christian Alden Jacobs" <notifications@github.com>
wrote:

Verify Project task fails with:

WD php: Error: Call to undefined function provision_process() in
getBranchesAndTags() (line 92 of
/var/aegir/devmaster-1.4.0/profiles/devmaster/modules/devshop/devshop_projects/drush/contexts.inc).

Drush command terminated abnormally due to an unrecoverable error.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opendevshop/devshop/issues/311>, or mute the thread

**Comment by caldenjacobs** [comment]
There's definitely something odd going on with Provision

**Comment by hubdrop-user** [comment]
It's not odd, it's new features. :)

I wrote that function, let me know if updating provision worked?

**Comment by caldenjacobs** [comment]
Hmm.. drush dl provision didn't solve it

**Comment by hubdrop-user** [comment]
What version did it download and where?

**Comment by caldenjacobs** [comment]
Running 'drush dl provision' returns:
 
`No release history available for provision 8.x.                      [error]
Could not download requested project(s).                             [error]`

'drush @hostmaster dl provision-7.x-3.160' drops it in /var/aegir/devmaster-1.4.0/sites/all/modules/provision

What should it be doing?

**Comment by jonpugh** [comment]
wow, that's why I shouldn't reply by email

@caldenjacobs Provision is a drush extension, that's the wrong place.

Try `drush dl provision-7.x-3.160`

**Comment by jonpugh** [comment]
Yeah, drush is a little annoying there. It only looks for modules in the 8.x version space. You can also call `drush dl provision-7.x-3.160`

**Comment by caldenjacobs** [comment]
Ah, that makes sense. 

drush dl provision-7.x-3.160 sends it to /var/aegir which can't be right either. 

Where should I be dropping it?

**Comment by jonpugh** [comment]
The scripts put it in `/var/aegir/.drush/commands`

https://github.com/opendevshop/ansible-role-devmaster/blob/master/tasks/main.yml#L63

**Comment by jonpugh** [comment]
@caldenjacobs I'd like to explore how your upgrade failed. The ansible role should install the specific version.

Is this a problem generally? or an edge case for your server...

**Comment by caldenjacobs** [comment]
I'll do some searching. This happened on an Ubuntu 16.04 box with no significant modifications since installing devshop, aside from some updates.

**Comment by ipumpkin** [comment]
Has the same issue.

**Comment by metalbote** [comment]
same here with devshop/server docker setup

**Comment by jonpugh** [comment]
Provision drush project must be updated to latest version to fix this.

Most users should be upgraded by now. If not, getting the latest provision drush project will resolve this:

`drush dl provision-7.x` should do the trick.
