### ISSUE TITLE
What is the username and password to enter the administration of devshop (docker)?

### ISSUE THREAD

**Issue by Gonzalo2683** [opendevshop/devshop#407]
Hi, I'm trying devshop with docker, I can't find it anywhere is the username and password to enter the devshop administration.

**Comment by jonpugh** [comment]
This is because there really isn't one. For historical security reasons, the Aegir Hostmaster "admin" user (uid:1) gets a long random password set that is never shown.

It is poorly documented, but expected that you, as the admin of your Aegir instance will always have drush access, so you can always run `drush @hostmaster uli` to get a new login reset link.

So, to get in right now, use this command as the `aegir` user: `drush @hostmaster uli`.

I want to improve this, it's a common source of confusion. Here's what we can do:

- Output a more visible message a the end of the install script explaining this.
- Add a documentation page dedicated to user policy, explaining why this is setup this way.
- Add an option to the `drush hostmaster-install` command to show the generated admin password once in the output logs. Perhaps it should be the default to hide it, but it should also be possible for those that wish to get the password.
- Add an option to the `drush hostmaster-install` command to set a password from the command line, such as `--admin-pass=12345`

What do you think?

Once the PR for the monorepo at #405 is merged, these will be relatively simple tasks to work on..

**Comment by jonpugh** [comment]
What would be the best solution here?

1. Randomly generate a password and print it out in the docker logs?
2. Force the password to be admin/admin? 
3. How to handle both? Install script should default a server to secure, but ease of use in certain situations takes precedence. Look at Rancher as an example: When you first setup Rancher server, there is no authentication required AT ALL, and it warns you to set it up as soon as possible.
