### ISSUE TITLE
Custom Git URL results in Failed Github Authentication

### ISSUE THREAD

**Issue by FatGuyLaughing** [opendevshop/devshop#486]
## Reproduce

1. Create a project with a custom git url.
2. After submitting the `Step 2: Settings` form, the error below will show up.

```
GitHub authentication failed. Check your token at DevShop GitHub Settings. The error was: Not Found
```

**Comment by jonpugh** [comment]
This is with no github token added, right?

**Comment by jonpugh** [comment]
That should do it, @FatGuyLaughing. 

Let me know!

**Comment by FatGuyLaughing** [comment]
Yes that was with no github token added. I'll test this as soon as I'm done with lunch.

**Comment by jonpugh** [comment]
Ahh, ok, I see the confusion.

This might appear as a bug, but what I think was happening is that you were using the wrong token and that token did not have access to the repo.

GitHub returns 404 instead of 403.

This is a bit of tribal knowledge.

We should detect this and remind users of this potential problem.

However, it should be very mitigated by the newish ability to select existing GitHub projects from a list, I will keep this report open as UX feedback.

Thanks for reporting!
