### ISSUE TITLE
Can multiple php versions be run per each site or platform deployed?

### ISSUE THREAD

**Issue by socialnicheguru** [opendevshop/devshop#713]

**Comment by jonpugh** [comment]
While I support the idea, I don't think it's going to happen for a while. 

The problem is making sure PHP versions for CLI match the servers.

Doing so in existing aegir architecture would be very hard. Backend tasks AND backend CLI would have to change the PHP they run with.

I just updated devshop to default to 8.1. 

Better practice to keep your sites up to date than hold back PHP and keep your sites stuck in the past on unsupported versions.
